### PR TITLE
Remove `urls` class from `UserAccount` model in `testapp`

### PR DESCRIPTION
**Pull request by samitnuk**
It is never used for tests - only adds additional import.

### CODE REVIEW

**Comment by rsinger86** [comment]
thanks!

**Comment by rsinger86** [comment]
Actually, even though it's not directly used, it does serve one purpose: making sure that the regular functionality isn't broken. A while back, I had to tweak some things internally to ensure that urlman was compatible with this package.

**Comment by samitnuk** [comment]
Hi, @rsinger86. Thank you for the explanation. Should we close this PR then?

**Comment by rsinger86** [comment]
Yes, thanks!

**Pull request closed without merging**
