### PR TITLE
Implement priority to hooks

### PR DESCRIPTION
**Pull request by EnriqueSoria**
...as discussed in #95 

What do you think of this approach? 

I have chosen that `priority=0` is maximum priority, also I have added some priorities to constant values so end users doesn't have to think about the implementation (`DEFAULT_PRIORITY`, `HIGHEST_PRIORITY`, etc...)

Feel free to comment, suggest or edit whatever

### CODE REVIEW

**Comment by rsinger86** [comment]
@EnriqueSoria this looks great, thank you. I also like the dataclass usage to encapsulate a hooked method.

The routine to gather up hooked methods to fire has gotten complex over the years.  My only suggestion would be to move the sorting of the `method._hooked` list out of `_get_hooked_methods` to simplify this Also, this order is static for lifetime of application doesn't need to be done each time. 

It seems like we could move the sorting to the decorator here:
https://github.com/rsinger86/django-lifecycle/blob/master/django_lifecycle/decorators.py#L83

Each time a specs dict is add to the `_hooked` list, we could resort it based on priority

**Comment by EnriqueSoria** [comment]
> @EnriqueSoria this looks great, thank you. I also like the dataclass usage to encapsulate a hooked method.
> 
> The routine to gather up hooked methods to fire has gotten complex over the years. My only suggestion would be to move the sorting of the `method._hooked` list out of `_get_hooked_methods` to simplify this Also, this order is static for lifetime of application doesn't need to be done each time.
> 
> It seems like we could move the sorting to the decorator here: https://github.com/rsinger86/django-lifecycle/blob/master/django_lifecycle/decorators.py#L83
> 
> Each time a specs dict is add to the `_hooked` list, we could resort it based on priority

I've been able to move hook sorting to the decorator, as you said, but we need to keep reordering hooked methods at the end of `_get_hooked_methods`

**Comment by rsinger86** [comment]
@EnriqueSoria great, thank you. These are really impressive upgrades. 

I'm assuming the path forward is merging in your hook config refactor branch, then reintegrate this priority hooks branch with it. 

Does that sound right?

**Comment by EnriqueSoria** [comment]
> @EnriqueSoria great, thank you. These are really impressive upgrades.
> 
> I'm assuming the path forward is merging in your hook config refactor branch, then reintegrate this priority hooks branch with it.
> 
> Does that sound right?

It's up to you. Merge one branch and I will update the other with the changes.

**Comment by rsinger86** [comment]
Ok, the other branch has been merged.

This is such a fantastic improvement, thank you!

**Pull request merged**
