### PR TITLE
Fix before/after create hook for a custom PKs

### PR DESCRIPTION
**Pull request by atugushev**
Using `_state.adding` might be a better solution to determine whether a model is a new.
See https://stackoverflow.com/a/35647389/1529164

### CODE REVIEW

**Comment by atugushev** [comment]
Hello @rsinger86, gentle ping. Any feedback on this PR?

**Comment by rsinger86** [comment]
Looks great. Thanks! This has been merged/released.

**Comment by atugushev** [comment]
Awesome! Thank you.

**Comment by atugushev** [comment]
@rsinger86 

It's seems the release wasn't upload to pypi, see https://pypi.org/project/django-lifecycle/#history

**Pull request merged**
